# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f07f256411934119ed368c8416db0d412397478d0db689bdab30a69bcd54d996607d0dfa89d0b4dbc73cc6e4b037c7b65a91f56985851c53b1f3d4c57f4a2c5e

test:
  secret_key_base: 50d07fb93cfb093b16a2d2b628d5d453c3123ddcb69f18533a578ac6463a1bc7a64783c02c78d48a6f17239ee22da7792a7fa09587dcbac4cec1db3d4875d74c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
